admin_1/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome_admin');
})->name('welcome');
Route::post('/logout','Admin\LoginController@logout')->name('logout');
Route::get('/home','HomeController@index')->name('home')->middleware('check_admin');
Route::get('/home/categories','CategoryController@index')->name('list_category')->middleware('check_admin');
Route::resource('/home/categories','Admin\CategoriesController',['as'=>'home'])->middleware('check_admin');
Route::resource('/home/vungmien','Admin\VungmienController',['as'=>'home'])->middleware('check_admin');
Route::resource('/home/baiviet','Admin\BaivietController',['as'=>'home'])->middleware('check_admin');
Route::resource('/home/nguoidung','Admin\NguoidungController',['as'=>'home'])->middleware('check_admin');
Route::get('/authlogin','Admin\LoginController@getAuthLogin')->name('getlogin');
Route::post('/authlogin','Admin\LoginController@postAuthLogin')->name('postlogin');
Route::get('/search/Categories','Admin\CategoriesController@search');
Route::get('/search/Baiviet','Admin\BaivietController@search');
Route::get('/search/Nguoidung','Admin\NguoidungController@search');
Route::get('/search/Vungmien','Admin\VungmienController@search');

admin_1/app/Vungmiens.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
class Vungmiens extends Model
{
    protected $table="vungmiens";
    public $timestamps=false;
    protected $fillable=[
        'ten_vungmien',
        'noidung',
        'action',
        'created_at',
        'updated_at',
    ];
    public function baiviets(){
        return $this->hasmany('App\baiviets');
    }
}

admin_1/app/Http/Controllers/Admin/VungmienController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Vungmiens;
use Validator;
use DB;
class VungmienController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Responses
     */
    public function __construct(){
        $this->middleware('auth:nguoidung');
    }
    public function index()
    {
        $vungmien = DB::table('vungmiens')->paginate('3');
        return view('admin.vungmien.index',compact('vungmien'));
        //$arr['vungmien']=Vungmiens::all();
        //return view('admin.vungmien.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.vungmien.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,Vungmiens $vungmien)
    {
        $rule=['ten_vungmien'=>'required|min:3','noidung'=>'required|min:10'];
        $validator=Validator::make($request->all(),$rule);
        if($validator->fails()){
        return redirect()->route('home.vungmien.create');
    }
        $vungmien->ten_vungmien=$request->ten_vungmien;
        $vungmien->noidung=$request->noidung;
        $vungmien->save();
        return redirect()->route('home.vungmien.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Vungmiens $vungmien)
    {
        $arr['vungmien']=$vungmien;
        return view('admin.vungmien.edit')->with($arr);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Vungmiens $vungmien)
    {
        $rule=['ten_vungmien'=>'required|min:3','noidung'=>'required|min:10'];
        $validator=Validator::make($request->all(),$rule);
        if($validator->fails()){
        return redirect()->route('home.vungmien.create');
    }
        $vungmien->ten_vungmien=$request->ten_vungmien;
        $vungmien->noidung=$request->noidung;
        $vungmien->save();
        return redirect()->route('home.vungmien.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Vungmiens::destroy($id);
        return redirect()->route('home.vungmien.index');
    }
    public function search(){
        $search_text=$_GET['query'];
        $vungmien=Vungmiens::where('ten_vungmien','LIKE','%'.$search_text.'%')->paginate('3');
        if(!$search_text)
            return redirect()->route('home.vungmien.index');
        return view('admin.vungmien.index',compact('vungmien'));
    }
}

admin_1/resources/views/admin/vungmien/create.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark">Thêm vùng miền</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
					<li class="breadcrumb-item active">Thêm vùng miền</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>    

<section class="content">
	<div class="container-fluid">
		<form method="post" action="{{route('home.vungmien.store')}}">
			<input type="hidden" name="_token" value="{{csrf_token()}}">
			<div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Tên</label>
					<div class="col-md-6"><input type="text" name="ten_vungmien" class="form-control" required></div>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Nội dung</label>
					<div class="col-md-6"> <textarea name="noidung" class="form-control" required></textarea> </div>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value=" Save">
			</div>
		</form>
	</div>
</section>
@endsection

admin_1/resources/views/admin/vungmien/edit.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark">Sửa vùng miền</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
					<li class="breadcrumb-item active">Sửa vùng miền</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>    

<section class="content">
	<div class="container-fluid">
		<form method="post" action="{{route('home.vungmien.update',$vungmien->id)}}">
		@method('PUT')
			<input type="hidden" name="_token" value="{{csrf_token()}}">
			<div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Tên</label>
					<div class="col-md-6"><input type="text" name="ten_vungmien" class="form-control" value="{{$vungmien->ten_vungmien}}" required></div>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Nội dung</label>
					<div class="col-md-6"> <textarea name="noidung" class="form-control" required>{{$vungmien->noidung}}</textarea> </div>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value=" Save">
			</div>
		</form>
	</div>
</section>
@endsection

admin_1/resources/views/admin/vungmien/index.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-4">
                <h1 class="m-0 text-dark">Vùng miền</h1>
            </div><!-- /.col -->
            <div class="col-sm-4">
                <form type="get" action="{{url('/search/Vungmien')}}">
                    <div class="input-group mb-3">
                        <input name="query" type="text" class="form-control" placeholder="Tên">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search" aria-hidden="true"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div><!-- /.col -->
            <div class="col-sm-4">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Vùng miền</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<section class="content">
    <div class="container-fluid">
        <p>
            <a href="{{route('home.vungmien.create')}}" class="btn btn-primary">Thêm mới vùng miền</a>
        </p>

        <table class="table table-bordered table-striped">
            <tr>
                <th>ID</th>
                <th>Tên</th>
                <th>Nội dung</th>
                <th>Action</th>
            </tr>
            @foreach($vungmien as $value)
            <tr>
                <td>{{$value->id}}</td>
                <td>{{$value->ten_vungmien}}</td>
                <td>{{$value->noidung}}</td>
                <td><a href="{{route('home.vungmien.edit',$value->id)}}" class="btn btn-success">Edit</a>
                    <a href="javascript:void(0)" onclick="$(this).parent().find('form').submit()"
                        class="btn btn-secondary">Delete</a>
                    <form action="{{route('home.vungmien.destroy',$value->id )}}" method="post">
                        @method('DELETE')
                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                    </form>
                </td>
            </tr>
            @endforeach
        </table>
        <div class="row">
            <div class="col-sm-6"> </div>
            <div class="col-sm-6"> {{$vungmien->links()}}</div>
        </div>
    </div>
</section>
@endsection