admin_1/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome_admin');
})->name('welcome');
Route::post('/logout','Admin\LoginController@logout')->name('logout');
Route::get('/home','HomeController@index')->name('home')->middleware('check_admin');
Route::get('/home/categories','CategoryController@index')->name('list_category')->middleware('check_admin');
Route::resource('/home/categories','Admin\CategoriesController',['as'=>'home'])->middleware('check_admin');
Route::resource('/home/vungmien','Admin\VungmienController',['as'=>'home'])->middleware('check_admin');
Route::resource('/home/baiviet','Admin\BaivietController',['as'=>'home'])->middleware('check_admin');
Route::resource('/home/nguoidung','Admin\NguoidungController',['as'=>'home'])->middleware('check_admin');
Route::get('/authlogin','Admin\LoginController@getAuthLogin')->name('getlogin');
Route::post('/authlogin','Admin\LoginController@postAuthLogin')->name('postlogin');
Route::get('/search/Categories','Admin\CategoriesController@search');
Route::get('/search/Baiviet','Admin\BaivietController@search');
Route::get('/search/Nguoidung','Admin\NguoidungController@search');
Route::get('/search/Vungmien','Admin\VungmienController@search');

admin_1/app/Baiviets.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use DB;
use app\vungmiens;
use app\category;
class Baiviets extends Model
{

    protected $table="baiviets";
    public $timestamps=false;
    protected $fillable=[
    'ten',
    'chude_id',
    'vungmien_id',
    'nguyenlieu',
    'soche',
    'thuchien',
    'cachdung',
    'action',
    'created_at',
    'updated_at',
    'hinhanh',
    'ten_vungmien',
    'title',
];
public function Vungmiens(){
    return $this->belongsTo('App\vungmiens','vungmien_id');
}
    public function category(){
        return $this->belongsTo('App\category');
    }
    
}

admin_1/app/Http/Controllers/Admin/BaivietController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Category;
use App\Vungmiens;
use App\Baiviets;
use DB;
use Validator;
class BaivietController extends Controller
{
    public function __construct(){
        $this->middleware('auth:nguoidung');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // $arr['baiviet']=Baiviets::all();
        // return view('admin.baiviet.index')->with($arr);
        $baiviet=Baiviets::with('category')->paginate(2); 
        $category=Category::all();
        return view('admin.baiviet.index',compact('category','baiviet'));
        //return view('admin.baiviet.index',['baiviet'=>$data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $arr['categories']=Category::all();
        $arr['vungmiens']=Vungmiens::all();
        return view('admin.baiviet.create')->with($arr);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request,Baiviets $baiviet)
    {
        $rule=['ten'=>'required|min:3',
                'nguyenlieu'=>'required|min:10', 
                'soche'=>'required|min:10',
                'thuchien'=>'required|min:10',
                'cachdung'=>'required|min:3',   
                'hinhanh'=>'required'];
        $validator=Validator::make($request->all(),$rule);
        if($validator->fails()){
            return redirect()->route('home.baiviet.create');
        }
        if($request->hinhanh->getClientOriginalName())
        {
            $ext= $request->hinhanh->getClientOriginalExtension();
            $file = date('YmdHis').rand(1,9999).'.'.$ext;
            $request->hinhanh->storeAs('public/baiviet',$file);
        }
        else{
            $file='';
        }
        $baiviet->hinhanh=$file;
        $baiviet->ten=$request->ten;
        $baiviet->nguyenlieu=$request->nguyenlieu;
        $baiviet->soche=$request->soche;
        $baiviet->thuchien=$request->thuchien;
        $baiviet->cachdung=$request->cachdung;
        $baiviet->category_id=$request->category_id;
        $baiviet->vungmien_id=$request->vungmien_id;
        $baiviet->save();
        return redirect()->route('home.baiviet.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Baiviets $baiviet )
    {
        $arr['baiviet']=$baiviet;
        $arr['categories']=Category::all();
        $arr['vungmiens']=Vungmiens::all();
        return view('admin.baiviet.edit')->with($arr);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Baiviets $baiviet)
    {
         $rule=['ten'=>'required|min:3',
                'nguyenlieu'=>'required|min:10', 
                'soche'=>'required|min:10',
                'thuchien'=>'required|min:10',
                'cachdung'=>'required|min:3',   
                'hinhanh'=>'required'];
        $validator=Validator::make($request->all(),$rule);
        if($validator->fails()){
            return redirect()->route('home.baiviet.create');
        }
        if(isset($request->hinhanh)&&$request->hinhanh->getClientOriginalName())
        {
            $ext= $request->hinhanh->getClientOriginalExtension();
            $file = date('YmdHis').rand(1,9999).'.'.$ext;
            $request->hinhanh->storeAs('public/baiviet',$file);
        }
        else{
            if(!$baiviet->hinhanh)
                $file='';
            else
                $file=$baiviet->hinhanh;
        }
        $baiviet->hinhanh=$file;
        $baiviet->ten=$request->ten;
        $baiviet->nguyenlieu=$request->nguyenlieu;
        $baiviet->soche=$request->soche;
        $baiviet->thuchien=$request->thuchien;
        $baiviet->cachdung=$request->cachdung;
        $baiviet->category_id=$request->category_id;
        $baiviet->vungmien_id=$request->vungmien_id;
        $baiviet->save();
        return redirect()->route('home.baiviet.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Baiviets::destroy($id);
        return redirect()->route('home.baiviet.index');
    }
    public function search(){
        $search_text=$_GET['query'];
        $category=Category::all();
        $baiviet=Baiviets::where('ten','LIKE','%'.$search_text.'%')->with('category')->paginate('2');
        if($search_text == null)
        return redirect()->route('home.baiviet.index');
        return view('admin.baiviet.index',compact('category','baiviet'));
    }
}

admin_1/resources/views/admin/baiviet/create.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark">Thêm bài viết</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
					<li class="breadcrumb-item active">Thêm bài viết</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>    

<section class="content">
	<div class="container-fluid">
		<form method="post" runat="server" action="{{route('home.baiviet.store')}}" enctype="multipart/form-data">
			<input type="hidden" name="_token" value="{{csrf_token()}}">
			<div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Tên</label>
					<div class="col-md-6"><input type="text" name="ten" class="form-control"required></div>
					<div class="clearfix"></div>
				</div>
			</div>
            <div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Nguyên Liệu</label>
					<div class="col-md-6"><textarea name="nguyenlieu" class="form-control" required></textarea></div>
					<div class="clearfix"></div>
				</div>
			</div>
            <div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Sơ chế</label>
					<div class="col-md-6"><textarea name="soche" class="form-control" required></textarea></div>
					<div class="clearfix"></div>
				</div>
			</div>
            <div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Thực hiện</label>
					<div class="col-md-6"><textarea name="thuchien" class="form-control" required></textarea></div>
					<div class="clearfix"></div>
				</div>
			</div>
            <div class="form-group">	
				<div class="row">	
					<label class="col-md-3">cách dùng</label>
					<div class="col-md-6"> <textarea name="cachdung" class="form-control" required></textarea> </div>
					<div class="clearfix"></div>
				</div>
			</div>
            <div class="form-group">	 
				<div class="row">	
					<label class="col-md-3">Hình ảnh</label>
					<div class="col-md-6">
					<input type='file' id="imgInp" name="hinhanh"/>
					<br/>
 						 <img id="blah" src="#" alt="your image" class=""width="200" height="150" />
					</div> 
				</div>
			</div>

            <div class="form-group">	
				<div class="row">
                <label class="col-md-3"></label>	
                <select name="category_id" class="form-control col-md-6 ">
                     <!-- <option value="">Chọn thể loại</option>  -->
                     @foreach($categories as $category)
                     <option value="{{ $category->id}}">{{$category->title}}</option>
                     @endforeach
                 </select>
					<div class="clearfix"></div>
				</div>
			</div>

            <div class="form-group">	
				<div class="row">
                <label class="col-md-3"></label>	
                <select name="vungmien_id" class="form-control col-md-6 ">
                     <!-- <option value="">Chọn vùng miền</option>  -->
                     @foreach($vungmiens as $vungmien)
                     <option value="{{$vungmien->id}}">{{$vungmien->ten_vungmien}}</option>
                     @endforeach
                 </select>
					<div class="clearfix"></div>
				</div>
			</div>
            
            
			<div class="form-group">
				<input type="submit" class="btn btn-success" value=" Save">
			</div>
		</form>
	</div>
</section>
@endsection
@section('scripts')
<script>
    function readURL(input) {
  if (input.files && input.files[0]) {
    var reader = new FileReader();
    
    reader.onload = function(e) {
      $('#blah').attr('src', e.target.result);
    }
    
    reader.readAsDataURL(input.files[0]); // convert to base64 string
  }
}

$("#imgInp").change(function() {
  readURL(this);
});
</script>
@endsection

admin_1/resources/views/admin/baiviet/edit.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark">Sửa bài viết</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
					<li class="breadcrumb-item active">Sửa bài viết</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>    

<section class="content">
	<div class="container-fluid">
		<form method="post" action="{{route('home.baiviet.update',$baiviet->id)}}" enctype="multipart/form-data">
        @method('PUT')
			<input type="hidden" name="_token" value="{{csrf_token()}}">
			<div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Tên</label>
					<div class="col-md-6"><input type="text" name="ten" class="form-control" value="{{$baiviet->ten}}"></div>
					<div class="clearfix"></div>
				</div>
			</div>
            <div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Nguyên Liệu</label>
					<div class="col-md-6">
                        <textarea name="nguyenlieu" class="form-control">{{$baiviet->nguyenlieu}}</textarea>
                    </div>
					<div class="clearfix"></div>
				</div>
			</div>
            <div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Sơ chế</label>
					<div class="col-md-6">
                    <textarea name="soche" class="form-control">{{$baiviet->soche}}</textarea>
                    </div>
					<div class="clearfix"></div>
				</div>
			</div>
            <div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Thực hiện</label>
					<div class="col-md-6">
                        <textarea name="thuchien" class="form-control">{{$baiviet->thuchien}}</textarea>
                    </div>
					<div class="clearfix"></div>
				</div>
			</div>
            <div class="form-group">	
				<div class="row">	
					<label class="col-md-3">cách dùng</label>
					<div class="col-md-6">
                    <textarea name="cachdung" class="form-control" >{{$baiviet->cachdung}}</textarea>
                    </div>
					<div class="clearfix"></div>
                   
				</div>
			</div>
            <div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Hình ảnh</label>
					<div class="col-md-9"><input type="file" name="hinhanh"></div>
                    <div class="clearfix"></div>
                    @if($baiviet->hinhanh)
                    <div class="col-md-3"></div>
                    <div class="col-md-9">
                     <img src="{{asset('storage/baiviet/'.$baiviet->hinhanh)}}" style="width:150px">
                    </div>
                    <div class="clearfix"></div>
                    @endif
				</div>
			</div>
            <div class="form-group">	
				<div class="row">
                <label class="col-md-3"></label>	
                <select name="category_id" class="form-control col-md-6 ">
                     <!-- <option value="">Chọn thể loại</option>  -->
                     @foreach($categories as $category)
                     <option value="{{$category->id}}"
                        @if($category->id==$baiviet->category_id)
                            selected
                         @endif
						 >{{$category->title}}</option>
                     @endforeach
                 </select>
					<div class="clearfix"></div>
				</div>
			</div>

			<div class="form-group">	
				<div class="row">
                <label class="col-md-3"></label>	
                <select name="vungmien_id" class="form-control col-md-6 ">
                     <!-- <option value="">Chọn vùng miền</option>  -->
                     @foreach($vungmiens as $vungmien)
                     <option value="{{$vungmien->id}}"
                        @if($vungmien->id==$baiviet->vungmien_id)
                            selected
                         @endif
						 >{{$vungmien->ten_vungmien}}</option>
                     @endforeach
                 </select>
					<div class="clearfix"></div>
				</div>
			</div>

			<div class="form-group">
				<input type="submit" class="btn btn-success" value=" Save">
			</div>
		</form>
	</div>
</section>
@endsection

admin_1/resources/views/admin/baiviet/index.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-4">
                <h1 class="m-0 text-dark">Bài viết</h1>
            </div><!-- /.col -->
            <div class="col-sm-4">
                <form type="get" action="{{url('/search/Baiviet')}}">
                    <div class="input-group mb-3">
                        <input name="query" type="text" class="form-control" placeholder="Tên">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search" aria-hidden="true"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div><!-- /.col -->
            <div class="col-sm-4">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Bài viết</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<section class="content">
    <div class="container-fluid">
        <p>
            <a href="{{route('home.baiviet.create')}}" class="btn btn-primary">Thêm mới bài viết</a>
        </p>

        <table class="table table-bordered table-striped">
            <tr>
                <th>ID</th>
                <th>Ten</th>
                <th>HinhAnh</th>
                <th>ChuDe</th>
                <th>VungMien</th>
                <th>NguyenLieu</th>
                <th>SoChe</th>
                <th>ThucHien</th>
                <th>CachDung</th>
                <th>Action</th>
            </tr>
            @if(count($baiviet))
            @foreach($baiviet as $value)
            <tr>
                <td>{{$value->id}}</td>
                <td>{{$value->ten}}</td>
                <td><img src="{{asset('storage/baiviet/'.$value->hinhanh)}}" style="width:150px"></td>
                <td>{{$value->category->title}}</td>
                <td>{{$value->vungmiens->ten_vungmien}}</td>
                <td>{{$value->nguyenlieu}}</td>
                <td>{{$value->soche}}</td>
                <td>{{$value->thuchien}}</td>
                <td>{{$value->cachdung}}</td>
                <td><a href="{{route('home.baiviet.edit',$value->id)}}" class="btn btn-success">Edit</a>
                    <a href="javascript:void(0)" onclick="$(this).parent().find('form').submit()"
                        class="btn btn-secondary">Delete</a>
                    <form action="{{route('home.baiviet.destroy',$value->id )}}" method="post">
                        @method('DELETE')
                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                    </form>
                </td>
            </tr>
            @endforeach
            @else
            <tr>
                <td colspan="10">Không tìm thấy bài viết </td>
            </tr>
            @endif
        </table>
        <div class="row">
            <div class="col-sm-6"> </div>
            <div class="col-sm-6"> {{$baiviet->links()}}</div>
        </div>


    </div>
</section>
@endsection