admin_1/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome_admin');
})->name('welcome');
Route::post('/logout','Admin\LoginController@logout')->name('logout');
Route::get('/home','HomeController@index')->name('home')->middleware('check_admin');
Route::get('/home/categories','CategoryController@index')->name('list_category')->middleware('check_admin');
Route::resource('/home/categories','Admin\CategoriesController',['as'=>'home'])->middleware('check_admin');
Route::resource('/home/vungmien','Admin\VungmienController',['as'=>'home'])->middleware('check_admin');
Route::resource('/home/baiviet','Admin\BaivietController',['as'=>'home'])->middleware('check_admin');
Route::resource('/home/nguoidung','Admin\NguoidungController',['as'=>'home'])->middleware('check_admin');
Route::get('/authlogin','Admin\LoginController@getAuthLogin')->name('getlogin');
Route::post('/authlogin','Admin\LoginController@postAuthLogin')->name('postlogin');
Route::get('/search/Categories','Admin\CategoriesController@search');
Route::get('/search/Baiviet','Admin\BaivietController@search');
Route::get('/search/Nguoidung','Admin\NguoidungController@search');
Route::get('/search/Vungmien','Admin\VungmienController@search');

admin_1/app/Nguoidungs.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
class Nguoidungs extends Authenticatable
{
    use Notifiable;
    public function getAuthPassword(){
        return $this->matkhau;
    }
    protected $table="nguoidungs";
    public $timestamps=false;
    protected $fillable=[
        'gmail',
        'matkhau',
        'phanquyen',
        'ten',
        'action',
    ];
    protected $hidden = [
        'password', 'remember_token',
    ];
}

admin_1/app/Http/Controllers/Admin/NguoidungController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Nguoidungs;
use Validator;
use DB;
class NguoidungController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct(){
        $this->middleware('auth:nguoidung');
    }
    public function index()
    {
        $nguoidung = DB::table('nguoidungs')->where('phanquyen','0')->paginate('5');
        return view('admin.nguoidung.index',compact('nguoidung'));
        //$arr['nguoidung']=Nguoidungs::all();
        
        //return view('admin.nguoidung.index')->with($arr);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {       
        $arr['nguoidung']=Nguoidungs::all();
        return view('admin.nguoidung.create')->with($arr);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Nguoidungs $nguoidung)
    {
        $rule=['ten'=>'required|min:3',
                'gmail'=>'required|email',];
        $validator=Validator::make($request->all(),$rule);
        if($validator->fails()){
        return redirect()->route('home.nguoidung.create');
    }
        $nguoidung->ten=$request->ten;
        $nguoidung->gmail=$request->gmail;
        $nguoidung->matkhau=$request->matkhau;
        $nguoidung->phanquyen=0;
        $nguoidung->action=0;
        $nguoidung->save();
        return redirect()->route('home.nguoidung.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Nguoidungs $nguoidung)
    {
        $arr['nguoidung']=$nguoidung;
        return view('admin.nguoidung.edit')->with($arr);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,Nguoidungs $nguoidung)
    {
        $rule=['ten '=>'required|min:3',
                'gmail'=>'required|email'];
        $validator=Validator::make($request->all(),$rule);
        if($validator->fails()){
        return redirect()->route('home.nguoidung.create');
    }
        $nguoidung->ten=$request->ten;
        $nguoidung->gmail=$request->gmail;
        $nguoidung->matkhau=$request->matkhau;
        $nguoidung->phanquyen=$request->phanquyen;
        $nguoidung->action=$request->action;
        $nguoidung->save();
        return redirect()->route('home.nguoidung.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Nguoidungs::destroy($id);
        return redirect()->route('home.nguoidung.index');
    }
    public function search(){
        $search_text=$_GET['query'];
        $nguoidung=Nguoidungs::where('ten','LIKE','%'.$search_text.'%')->where('phanquyen','0')->paginate('4');
        if(!$search_text)
            return redirect()->route('home.nguoidung.index');
        return view('admin.nguoidung.index',compact('nguoidung'));
    }
}

admin_1/app/Http/Controllers/Api/NguoidungController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Nguoidungs;
class NguoidungController extends Controller
{
    public function Swap($id){
        $nguoidung =Nguoidungs::find($id);
        $nguoidung->action = !$nguoidung->action;
        $nguoidung->save();
        return response()->json($nguoidung,201);
    }
}

admin_1/resources/views/admin/nguoidung/create.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark">Thêm người dùng</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
					<li class="breadcrumb-item active">Thêm người dùng</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>    

<section class="content">
	<div class="container-fluid">
		<form method="post" action="{{route('home.nguoidung.store')}}" enctype="multipart/form-data">
			<input type="hidden" name="_token" value="{{csrf_token()}}">
			<div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Tên</label>
					<div class="col-md-6"><input type="text" name="ten" class="form-control" required></div>
					<div class="clearfix"></div>
				</div>
			</div>
            <div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Gmail</label>
					<div class="col-md-6"><input type="text" name="gmail" class="form-control" required></div>
					<div class="clearfix"></div>
				</div>
			</div>
            <div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Mật khẩu</label>
					<div class="col-md-6"><input type="text" name="matkhau" class="form-control" required></div>
					<div class="clearfix"></div>
				</div>
			</div>

            <div class="form-group">	
				<div class="row">
                <label class="col-md-3">Phân quyền</label>	
                <select name="nguoidung_id" class="form-control col-md-6">
                     <option value="0">User</option>
                     <option value="1">Admin</option>              
                 </select>
					<div class="clearfix"></div>
				</div>
			</div>

			<div class="form-group">
				<input type="submit" class="btn btn-success btn-action" value=" Save">
			</div>
		</form>
	</div>
</section>
@endsection
<script language="javascript">
	// function swap(var $id){
	// 	$("#"+$id).attr('class','btn btn-outline-success');
	// }
	
$(".btn-action").on('click',function(e) {
	e.preventDefault();
	var id =($(this).attr("id"));
    $.ajax({
		type: "POST",
		dataType: "json",
		url: 'http://192.168.42.102:8000/api/nguoidungs/swap/'+id,
        success: function(data) {
			console.log(data);
			$(".btn-action#"+data.id).val((data.action==true)?'Mở Khóa':'Khóa');
			$(".btn-action#"+data.id).attr('class',(data.action==true)?'btn-action btn btn-outline-success':'btn-action btn btn-outline-danger');
        },
        error: function() {
            alert('Lỗi chương trình');
        }
    });
})
</script>

admin_1/resources/views/admin/nguoidung/edit.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark">Edit Categories</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
					<li class="breadcrumb-item active">Edit Categories</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>    

<section class="content">
	<div class="container-fluid">
		<form method="post" action="{{route('home.nguoidung.update',$nguoidung->id)}}" enctype="multipart/form-data">
		@method('PUT')
			<input type="hidden" name="_token" value="{{csrf_token()}}">
			<div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Tên</label>
					<div class="col-md-6"><input type="text" name="ten" class="form-control" required value="{{$nguoidung->ten}}"></div>
					<div class="clearfix"></div>
				</div>
			</div>
            <div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Gmail</label>
					<div class="col-md-6"><input type="text" name="gmail" class="form-control" required value="{{$nguoidung->gmail}}"></div>
					<div class="clearfix"></div>
				</div>
			</div>
            <div class="form-group">	
				<div class="row">	
					<label class="col-md-3">Mật khẩu</label>
					<div class="col-md-6"><input type="text" name="matkhau" class="form-control" required value="{{$nguoidung->matkhau}}"></div>
					<div class="clearfix"></div>
				</div>
			</div>

            <div class="form-group">	
				<div class="row">
                <label class="col-md-3">Phân quyền</label>	
                <select name="phanquyen" class="form-control col-md-6">
                     <option value="0">User</option>
                     <option value="1">Admin</option>              
                 </select>
					<div class="clearfix"></div>
				</div>
			</div>

            <div class="form-group">	
				<div class="row">
                <label class="col-md-3">Trạng thái</label>	
                <select name="action" class="form-control col-md-6 ">
                     <option value="0">Mở khóa</option>
                     <option value="1">Khóa</option>              
                 </select>
					<div class="clearfix"></div>
				</div>
			</div>
			<div class="form-group">
				<input type="submit" class="btn btn-success" value=" Save">
			</div>
		</form>
	</div>
</section>
@endsection

admin_1/resources/views/admin/nguoidung/index.blade.php
@extends('layouts.dashboard')
@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-4">
            <div class="col-sm-4">
                <h1 class="m-0 text-dark">Người dùng</h1>
            </div><!-- /.col -->
            <div class="col-sm-4">
                <form type="get" action="{{url('/search/Nguoidung')}}">
                    <div class="input-group mb-3">
                        <input name="query" type="text" class="form-control" placeholder="Tên">
                        <div class="input-group-append">
                            <button class="btn btn-navbar" type="submit">
                                <i class="fas fa-search" aria-hidden="true"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div><!-- /.col -->
            <div class="col-sm-4">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Người dùng</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>

<section class="content">
    <div class="container-fluid">
        <p>
            <a href="{{route('home.nguoidung.create')}}" class="btn btn-primary">Thêm mới người dùng</a>
        </p>

        <table class="table table-bordered table-striped">
            <tr>
                <th>ID</th>
                <th>Tên</th>
                <th>Gmail</th>
                <th>Phân quyền</th>
                <th>Khóa</th>
                <th>Action</th>
            </tr>
            @foreach($nguoidung as $value)
            <tr>
                <td>{{$value->id}}</td>
                <td>{{$value->ten}}</td>
                <td>{{$value->gmail}}</td>
                <td>{{($value->phanquyen==1)?"admin":"user"}}</td>
                <td><input type="submit" value="{{($value->action==1)?"Mở Khóa":"Khóa"}}" id="{{$value->id}}"
                        type="button"
                        class="{{($value->action==0)?"btn-action btn btn-outline-danger":"btn-action btn btn-outline-success"}}" />
                </td>
                <td><a href="{{route('home.nguoidung.edit',$value->id)}}" class="btn btn-success">Edit</a>
                    <a href="javascript:void(0)" onclick="$(this).parent().find('form').submit()"
                        class="btn btn-secondary">Delete</a>
                    <form action="{{route('home.nguoidung.destroy',$value->id )}}" method="post">
                        @method('DELETE')
                        <input type="hidden" name="_token" value="{{csrf_token()}}">
                    </form>
                </td>
            </tr>
            @endforeach
        </table>
        <div class="row">
            <div class="col-sm-6"> </div>
            <div class="col-sm-6"> {{$nguoidung->links()}}</div>
        </div>
    </div>
</section>
@endsection
@section('scripts')
<script language="javascript">
// function swap(var $id){
// 	$("#"+$id).attr('class','btn btn-outline-success');
// }

$(".btn-action").on('click', function(e) {
    e.preventDefault();
    var id = ($(this).attr("id"));
    $.ajax({
        type: "GET",
        dataType: "json",
        url: 'https://coderthanhson.000webhostapp.com/api/nguoidungs/swap/' + id,
        success: function(data) {
            console.log(data);
            $(".btn-action#" + data.id).val((data.action == true) ? 'Mở Khóa' : 'Khóa');
            $(".btn-action#" + data.id).attr('class', (data.action == true) ?
                'btn-action btn btn-outline-success' : 'btn-action btn btn-outline-danger');
        },
        error: function() {
            alert('Lỗi chương trình');
        }
    });
})
</script>
@endsection